definitions:
  controller.SwaggerTextRequest:
    properties:
      content:
        description: 粘贴的Swagger内容字符串，必须为有效的OpenAPI内容
        type: string
    required:
    - content
    type: object
  model.APIEndpoint:
    properties:
      body:
        description: Request body for the endpoint
        type: string
      created_at:
        description: Timestamp when the endpoint was created
        type: string
      description:
        description: Detailed description of the endpoint
        type: string
      headers:
        allOf:
        - $ref: '#/definitions/model.StringMap'
        description: Headers associated with the endpoint
      id:
        description: Unique identifier for the endpoint
        type: integer
      method:
        description: HTTP method (GET, POST, etc.)
        type: string
      operation_id:
        description: Unique operation ID
        type: string
      parameters:
        description: List of parameters for the endpoint
        items:
          $ref: '#/definitions/model.APIParameter'
        type: array
      path:
        description: URL path of the endpoint
        type: string
      responses:
        description: Responses returned by the endpoint
        type: string
      summary:
        description: Brief summary of the endpoint
        type: string
      swagger_id:
        description: ID from the Swagger/OpenAPI specification
        type: integer
      tags:
        description: Tags associated with the endpoint
        type: string
      updated_at:
        description: Timestamp when the endpoint was last updated
        type: string
    type: object
  model.APIParameter:
    properties:
      in:
        description: Location of the parameter (e.g., query, path, header)
        type: string
      name:
        description: Name of the parameter
        type: string
      required:
        description: Whether the parameter is required
        type: boolean
      type:
        description: Data type of the parameter
        type: string
      value:
        description: Default value of the parameter
        type: string
    type: object
  model.StringMap:
    additionalProperties:
      type: string
    type: object
info:
  contact: {}
  description: MCP Manager Application Entry Point
  title: main.go
paths:
  /api/swagger/endpoint:
    put:
      consumes:
      - application/json
      parameters:
      - description: APIEndpoint数据
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.APIEndpoint'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.APIEndpoint'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 更新APIEndpoint
      tags:
      - Swagger
  /api/swagger/endpoint/{id}:
    delete:
      parameters:
      - description: APIEndpoint ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 删除指定APIEndpoint
      tags:
      - Swagger
    get:
      parameters:
      - description: APIEndpoint ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.APIEndpoint'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 根据ID查询APIEndpoint
      tags:
      - Swagger
  /api/swagger/endpoint/test:
    post:
      consumes:
      - application/json
      parameters:
      - description: APIEndpoint数据
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.APIEndpoint'
      - description: 服务器基础URL
        in: query
        name: base_url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 测试APIEndpoint
      tags:
      - Swagger
  /api/swagger/endpoints:
    get:
      parameters:
      - description: SwaggerID
        in: query
        name: swagger_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.APIEndpoint'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 查询指定swaggerID下所有APIEndpoint
      tags:
      - Swagger
  /api/swagger/parse:
    post:
      consumes:
      - application/json
      description: 上传Swagger内容并保存所有接口到数据库
      parameters:
      - description: Swagger内容
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/controller.SwaggerTextRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.APIEndpoint'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 解析并保存Swagger接口
      tags:
      - Swagger
  /api/swagger/validate/file:
    post:
      consumes:
      - multipart/form-data
      description: 上传Swagger文件并进行格式和内容校验
      parameters:
      - description: Swagger文件
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 通过文件上传校验Swagger文档
      tags:
      - Swagger
  /api/swagger/validate/text:
    post:
      consumes:
      - application/json
      description: 粘贴Swagger内容并进行格式和内容校验
      parameters:
      - description: Swagger内容
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/controller.SwaggerTextRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 通过文本内容校验Swagger文档
      tags:
      - Swagger
swagger: "2.0"
